language: python
python:
    - "2.7"

sudo: required

before_install:
    - sudo apt-get -qq install -y python-numpy python-scipy python-sklearn
    - pip install pytest pytest-cov codecov scipy --upgrade
    - python -c "import scipy; print scipy.__version__"

install:
    - pip install -r requirements.txt

script:
    - py.test --cov=.

after_success:
    - codecov
