language: python
python:
    - "2.7"

sudo: required

before_install:
    - sudo apt-get -qq install -y liblapack-dev gfortran
    - pip install pytest pytest-cov codecov

install:
    - pip install -r requirements.txt

script:
    - py.test --cov=.

after_success:
    - codecov
