language: python
python:
    - "2.7"

before_install:
    - sudo apt-get -qq update -y
# Maybe this helps?
    - sudo apt-get install python-numpy python-scipy
    - pip install pytest pytest-cov codecov

install:
    - pip install -r requirements.txt

script:
    - py.test --cov=.

after_success:
    - codecov
